services:
  - type: web
    name: sam-gameapi
    env: python
    plan: starter

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: PYTHON_VERSION
        value: 3.11

    # 👇 Persistencia
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
